image: cirrusci/flutter:2.10.0

stages:
  - lint
  - test
  - build
  - deploy

flutter_analyze:
  stage: lint
  script:
    - flutter analyze
    - flutter format -l 100 -n . --set-exit-if-changed

unit_test:
  stage: test
  script:
    - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev
    - flutter test test/*

build_web:
  stage: build
  script:
    - flutter build web --profile
    - sed -i 's#<base href="/">#<base href="/flutter-app/">#g' build/web/index.html
  artifacts:
    paths:
      - build/web

pages:
  stage: deploy
  script:
    - cp -r build/web public
  artifacts:
    paths:
      - public
  only:
    - dev

memri-docs:
  stage: deploy
  only:
    - dev
  trigger: memri/docs.memri.io

