targets:
  $default:
    builders:
      moor_generator:
        options:
          apply_converters_on_variables: true
          sqlite:
            modules:
              - fts5
          generate_connect_constructor: true
