name: memri
description: Memri Flutter application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version andthe builder number may be overridden in flutter
## build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.20+58

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moor: ^4.6.1+1
  sqlcipher_flutter_libs: ^0.5.1
  path_provider: ^2.0.8
  path: ^1.8.0
  uuid: ^3.0.5
  equatable: ^2.0.3
  html: ^0.15.0
  webview_flutter: ^3.0.0
  jiffy: ^5.0.0
  intl: ^0.17.0
  fl_chart: ^0.35.0
  mapbox_gl: ^0.15.0
  http: ^0.13.4
  flutter_contact: ^0.9.1+8
  permission_handler: ^8.3.0
  phone_number: ^0.12.0+1
  json_serializable: ^6.1.4
  flutter_secure_storage: ^5.0.2
  local_auth: ^1.1.10
  pointycastle: ^3.5.1
  idb_shim: ^2.0.1
  flutter_svg: ^1.0.3
  url_launcher: ^6.0.18
  json_annotation: ^4.4.0
  flutter_dropzone: ^3.0.5
  dotted_border: ^2.0.0+2
  pointer_interceptor: 0.9.1
  faker: ^2.0.0
  logger: ^1.1.0
  fluro: ^2.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  flutter_staggered_grid_view: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^4.6.0+1
  build_runner: ^2.1.7
  flutter_launcher_icons: "^0.9.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla-Regular.ttf
        - asset: assets/fonts/Karla-Italic.ttf
          style: italic
        - asset: assets/fonts/Karla-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Karla-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Karla-Bold.ttf
          weight: 700
        - asset: assets/fonts/Karla-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Karla-Medium.ttf
          weight: 500
        - asset: assets/fonts/Karla-Light.ttf
          weight: 300
        - asset: assets/fonts/Karla-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Karla-ExtraLight.ttf
          weight: 100

  assets:
    - assets/
    - assets/defaultCVU/named/
    - assets/defaultCVU/named/annotation/
    - assets/defaultCVU/renderer/
    - assets/defaultCVU/type/
    - assets/defaultCVU/plugins/
    - assets/demoAssets/
    - assets/HTMLResources/
    - assets/noteEditor/noteEditorDist/
    - assets/noteEditor/noteEditorDist/css/
    - assets/noteEditor/noteEditorDist/js/
    - assets/icons/
    - assets/images/
    - assets/cvuAceEditorDist/